Repository DeveloperAcademy-POSTECH/MC3-Team3-Puhaha, pull requests merged in 2022-07, with the labels that each got.

#6 Feature/lena/camera view
  Puhaha/Puhaha/Controllers/CameraViewController.swift
  Puhaha/Puhaha/Info.plist
Labels: 레나, FEAT

#5 [FEAT] Fork Tool 관련 Model 생성 #4
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
  Puhaha/Puhaha/Models/ForkTool.swift
Labels: FEAT, teemo, fork tool

#9 [FEAT] Camera View 사진촬영 기능 구현
  Puhaha/Puhaha/Controllers/CameraViewController.swift
Labels: 레나, FEAT

#11 Feature/colli/login view
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/AppDelegate.swift
  Puhaha/Puhaha/Controllers/SignInViewController.swift
  Puhaha/Puhaha/Global/Extensioon/CustomedLoginButton.swift
  Puhaha/Puhaha/Puhaha.entitlements
  Puhaha/Puhaha/SceneDelegate.swift
Labels: 콜리, FEAT

#13 Feature/lena/action sheet
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Info.plist
  Puhaha/Puhaha/Views/ActionSheetView.swift
Labels: 레나, FEAT

#18 Feature/colli/email-login-view
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Controllers/SignInViewController.swift
  Puhaha/Puhaha/Global/Extensioon/CustomedLoginButton.swift
Labels: 콜리, FEAT

#20 [FEAT] 밥먹언 앱 내 사용되는 색상을 UIColorExtension으로 추가
  Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
Labels: FEAT, 티모

#24 [FEAT] #23 식구가 올린 사진을 보여주는 뷰 추가
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Assets.xcassets/AddReactionButtonImage.imageset/AddReactionButtonImage.pdf
  Puhaha/Puhaha/Assets.xcassets/AddReactionButtonImage.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ReactionBackgroundImage.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ReactionBackgroundImage.imageset/ReactionBackgroundImage.pdf
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
  Puhaha/Puhaha/Global/UIViews/TagLabel.swift
  Puhaha/Puhaha/Models/Reaction.swift
  Puhaha/Puhaha/Models/Tag.swift
  Puhaha/Puhaha/Views/MealCardCollectionViewCell.swift
  Puhaha/Puhaha/Views/ReactionCollectionViewCell.swift
  Puhaha/Puhaha/Views/ReactionView.swift
Labels: 우기, FEAT

#26 [FEAT] #25 콕 찌르기 버튼 추가
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Assets.xcassets/PokeButtonBackgroundImgae.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/PokeButtonBackgroundImgae.imageset/PokeButtonBackgroundImgae.pdf
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Models/Meal.swift
  Puhaha/Puhaha/Views/EmptyMealCardView.swift
  Puhaha/Puhaha/Views/FamilyFilterCollectionViewCell.swift
  Puhaha/Puhaha/Views/MealCardCollectionViewCell.swift
Labels: 우기, FEAT

#30 [FEAT] 업로드 뷰 구현
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Puhaha/Puhaha/Controllers/CameraViewController.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
  Puhaha/Puhaha/Models/UploadTag.swift
  Puhaha/Puhaha/Views/ActionSheetView.swift
  Puhaha/Puhaha/Views/TagContentCollectionViewCell.swift
Labels: 레나, FEAT

#27 [FEAT] 콕 찌르기 도구 제작 뷰 구현
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Controllers/SignInViewController.swift
  Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
  Puhaha/Puhaha/Models/ForkTool.swift
  Puhaha/Puhaha/Models/PokingTool.swift
  Puhaha/Puhaha/Resources/BigFork.obj
  Puhaha/Puhaha/Resources/BigFork.scn
  Puhaha/Puhaha/Resources/BigSpoonVer2.obj
  Puhaha/Puhaha/Resources/BigSpoonVer2.scn
  Puhaha/Puhaha/Resources/BigWhisk.obj
  Puhaha/Puhaha/Resources/BigWhisk.scn
  Puhaha/Puhaha/Resources/Spatula.scn
  Puhaha/Puhaha/Resources/Tools.scn
  Puhaha/Puhaha/Views/DividerView.swift
Labels: FEAT, 티모, fork tool

#29 Feature/colli/setting view
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/SceneDelegate.swift
Labels: 콜리, FEAT

#38 [FEAT] 사진 라이브러리에서 UploadView로 이미지 데이터 연결
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Controllers/CameraViewController.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Views/ActionSheetView.swift
Labels: BUG, 레나, FEAT

#32 [FEAT] meal card filtering and view transition
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Assets.xcassets/PokeButtonBackgroundImage.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/PokeButtonBackgroundImage.imageset/PokeButtonBackgroundImage.pdf
  Puhaha/Puhaha/Assets.xcassets/TabBarColor/Contents.json
  Puhaha/Puhaha/Assets.xcassets/TabBarColor/TabBarIconSelectedColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/TabBarColor/TabBarIconUnSelectedColor.colorset/Contents.json
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController+DataSource.swift
  Puhaha/Puhaha/Controllers/MainViewController+Delegate.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
  Puhaha/Puhaha/Models/Tag.swift
  Puhaha/Puhaha/SceneDelegate.swift
  Puhaha/Puhaha/Views/EmptyMealCardView.swift
  Puhaha/Puhaha/Views/MealCardCollectionViewCell.swift
Labels: 우기, FEAT

#41 [FEAT] 가족 생성, 초대 뷰 에러 해결 후 다시 추가
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Assets.xcassets/BasicButtonBorderColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ButtonTitleColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/HelloMessageLabelColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/InfoLabelColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/RoomCodeTextColor.colorset/Contents.json
  Puhaha/Puhaha/Controllers/CreateFamilyViewController.swift
  Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
Labels: BUG, 우기, ADD

#42 [FIX] Upload View 오류 수정
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Info.plist
  Puhaha/Puhaha/Views/ActionSheetView.swift
Labels: BUG, 레나

#45 [CHORE] GoogleService-info
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/AppDelegate.swift
  Puhaha/Puhaha/GoogleService-Info.plist
Labels: 콜리

#44 [FEAT] 확정된 Hi-Fi를 기반으로 UI 구현 (#36)
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Assets.xcassets/ToolImages/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_fork.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_fork.imageset/silver_fork.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_spatula_ver2.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_spatula_ver2.imageset/silver_spatula_ver2.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_spoon.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_spoon.imageset/silver_spoon.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_whisk.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_whisk.imageset/silver_whisk.png
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Global/Extensioon/UIImage+Extension.swift
  Puhaha/Puhaha/Models/PokingTool.swift
  Puhaha/Puhaha/Views/PokingToolButton.swift
Labels: FEAT, ADD, 티모

#46 Feature/colli/setting view navigation
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Controllers/SignInViewController.swift
  Puhaha/Puhaha/Controllers/SingInViewControllerASDelegate.swift
  Puhaha/Puhaha/Global/Extensioon/UILabel+Extension.swift
Labels: 콜리, FEAT

#48 Feat/lena/main upload linking
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Info.plist
  Puhaha/Puhaha/Views/ActionSheetView.swift
Labels: 레나, ADD
