Repository DeveloperAcademy-POSTECH/MC3-Team3-Puhaha, pull requests merged in 2022-08, with the labels that each got.

#50 Feat/lena/main upload linking
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Camera+Extension.swift
Labels: 레나, ADD

#53 Feature/woogy/get firestore data
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Assets.xcassets/SampleImage/Silver_Spoon.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/SampleImage/Silver_Spoon.imageset/silver_spoon.pdf
  Puhaha/Puhaha/Assets.xcassets/Spoon.imageset/spoon.pdf
  Puhaha/Puhaha/Assets.xcassets/TagColor/Contents.json
  Puhaha/Puhaha/Assets.xcassets/TagColor/PastelBlueTagBackgroundColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/TagColor/PinkTagBackgroundColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/TagColor/VioletTagBackgroundColor.colorset/Contents.json
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController+DataSource.swift
  Puhaha/Puhaha/Controllers/MainViewController+Delegate.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Manager/StorageManager.swift
  Puhaha/Puhaha/Models/Family.swift
  Puhaha/Puhaha/Models/Meal.swift
  Puhaha/Puhaha/Models/Poke.swift
  Puhaha/Puhaha/Models/Reaction.swift
  Puhaha/Puhaha/Models/Tag.swift
  Puhaha/Puhaha/Models/User.swift
  Puhaha/Puhaha/Views/EmptyMealCardView.swift
  Puhaha/Puhaha/Views/FamilyFilterCollectionViewCell.swift
  Puhaha/Puhaha/Views/MealCardCollectionViewCell.swift
  Puhaha/Puhaha/Views/ReactionCollectionViewCell.swift
Labels: 우기, FEAT, ADD

#54 Feature/woogy/custom tab bar
  Puhaha/Puhaha/Assets.xcassets/EggFriedImage.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/EggFriedImage.imageset/EggFriedImage.pdf
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Camera+Extension.swift
  Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
Labels: 우기, FEAT, ADD

#56 [FIX] getLoginedUser, 중복 import 제거
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
Labels: BUG, 콜리

#58 [FEAT] add reaction feature
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Assets.xcassets/ReactionCollectionBackgroundColor.colorset/Contents.json
  Puhaha/Puhaha/Controllers/MainViewController+DataSource.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Models/Meal.swift
  Puhaha/Puhaha/Views/EmoticonCell.swift
  Puhaha/Puhaha/Views/EmoticonView.swift
  Puhaha/Puhaha/Views/MealCardCollectionViewCell.swift
Labels: 우기, FEAT, ADD

#59 [FEAT] 업로드뷰 firebase 데이터 연결
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Assets.xcassets/BasicButtonBorderColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ButtonTitleColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/InfoLabelColor.colorset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/TabIcon/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/Contents.json
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Camera+Extension.swift
  Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Manager/StorageManager.swift
  Puhaha/Puhaha/Models/Meal.swift
  Puhaha/Puhaha/Models/SigninManager.swift
  Puhaha/Puhaha/Models/Tag.swift
  Puhaha/Puhaha/Models/UploadTag.swift
Labels: 레나, FEAT

#60 Feature/woogy/achieving
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/Controllers/ArchiveViewController.swift
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Controllers/StatisticViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
  Puhaha/Puhaha/Global/Extensioon/ShadowUIViewExtension.swift
  Puhaha/Puhaha/Global/Extensioon/String+Extenstion.swift
  Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Manager/StorageManager.swift
  Puhaha/Puhaha/Views/ArchiveCell.swift
  Puhaha/Puhaha/Views/EmoticonView.swift
  Puhaha/Puhaha/Views/ReactionCollectionViewCell.swift
Labels: 우기, FEAT, ADD

#61 [FEAT] 파이어베이스 서버와 연결
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Models/PokingTool.swift
  Puhaha/Puhaha/Models/User.swift
Labels: FEAT, 티모

#63 [ADD] Setting View 화면연결
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
  Puhaha/Puhaha/Controllers/JoinFamilyViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/NameSettingViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
Labels: 레나, ADD, 티모

#66 [ADD] 찔러보기 도구 이미지 에셋 추가
  Puhaha/Puhaha/Assets.xcassets/ToolImages/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/black_fork.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/black_fork.imageset/black_fork.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/black_spatula.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/black_spatula.imageset/black_spatula.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/black_spoon.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/black_spoon.imageset/black_spoon.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/black_whisk.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/black_whisk.imageset/black_whisk.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/blue_fork.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/blue_fork.imageset/blue_fork.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/blue_spatula.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/blue_spatula.imageset/blue_spatula.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/blue_spoon.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/blue_spoon.imageset/blue_spoon.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/blue_whisk.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/blue_whisk.imageset/blue_whisk.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/purple_fork.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/purple_fork.imageset/purple_fork.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/purple_spatula.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/purple_spatula.imageset/purple_spatula.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/purple_spoon.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/purple_spoon.imageset/purple_spoon.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/purple_whisk.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/purple_whisk.imageset/purple_whisk.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_spatula.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/silver_spatula.imageset/silver_spatula_ver2.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/yellow_fork.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/yellow_fork.imageset/yellow_fork.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/yellow_spatula.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/yellow_spatula.imageset/yellow_spatula.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/yellow_spoon.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/yellow_spoon.imageset/yellow_spoon.png
  Puhaha/Puhaha/Assets.xcassets/ToolImages/yellow_whisk.imageset/Contents.json
  Puhaha/Puhaha/Assets.xcassets/ToolImages/yellow_whisk.imageset/yellow_whisk.png
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Models/PokingTool.swift
Labels: ADD, 티모

#65 실시간 데이터 연동
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/AppDelegate.swift
  Puhaha/Puhaha/Controllers/ArchiveViewController.swift
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController+DataSource.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Controllers/SingInViewControllerASDelegate.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
  Puhaha/Puhaha/Global/Extensioon/UIImage+Extension.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Manager/StorageManager.swift
  Puhaha/Puhaha/SceneDelegate.swift
  Puhaha/Puhaha/Views/ArchiveCell.swift
  Puhaha/Puhaha/Views/EmoticonView.swift
  Puhaha/Puhaha/Views/EmptyMealCardView.swift
  Puhaha/Puhaha/Views/MealCardCollectionViewCell.swift
Labels: 우기, FEAT

#68 [FEAT] 업로드뷰 동적 레이아웃 적용
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Global/UIViews/TagLabel.swift
  Puhaha/Puhaha/Views/TagContentCollectionViewCell.swift
Labels: 레나, FEAT

#70 [FIX] 설정뷰 및 로그인 오류 수정
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/AppDelegate.swift
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Controllers/NameEditingViewController.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
  Puhaha/Puhaha/Global/UIViews/TagLabel.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Models/SigninManager.swift
  Puhaha/Puhaha/SceneDelegate.swift
Labels: BUG, 레나, 콜리, 티모

#72 [HOTFIX] reload data immediately
  Puhaha/Puhaha/Controllers/ArchiveViewController.swift
  Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController+DataSource.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Controllers/NameEditingViewController.swift
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
Labels: BUG, 레나, 우기

#73 [HOTFIX] 계정 삭제 기능 추가 및 네비게이션 수정
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/SceneDelegate.swift
Labels: BUG, 레나, 우기, 티모

#74 초기 내비게이션 처리 수정
  Puhaha/Puhaha/AppDelegate.swift
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Controllers/ArchiveViewController.swift
  Puhaha/Puhaha/Controllers/CreateFamilyViewController.swift
  Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
  Puhaha/Puhaha/Controllers/JoinFamilyViewController.swift
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/NameEditingViewController.swift
  Puhaha/Puhaha/Controllers/NameSettingViewController.swift
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Controllers/SignInViewController.swift
  Puhaha/Puhaha/Controllers/SingInViewControllerASDelegate.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/SceneDelegate.swift
  Puhaha/Puhaha/Views/EmoticonView.swift
Labels: BUG, 우기

#75 Hotfix/resolve warning
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha/AppDelegate.swift
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
  Puhaha/Puhaha/Info.plist
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Models/Family.swift
  Puhaha/Puhaha/Models/PokingTool.swift
Labels: BUG

#76 [HOTFIX] Pad 버전 수정 / 콕 찌르기 기능 삭제
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
Labels: BUG

#77 [HOTFIX] version 1.0.1
  Puhaha/Puhaha.xcodeproj/project.pbxproj
  Puhaha/Puhaha.xcodeproj/xcshareddata/xcschemes/밥먹언?.xcscheme
  Puhaha/Puhaha/AppDelegate.swift
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
  Puhaha/Puhaha/Controllers/JoinFamilyViewController.swift
  Puhaha/Puhaha/Controllers/MainTabViewController.swift
  Puhaha/Puhaha/Controllers/MainViewController.swift
  Puhaha/Puhaha/Controllers/NameEditingViewController.swift
  Puhaha/Puhaha/Controllers/NameSettingViewController.swift
  Puhaha/Puhaha/Controllers/PokeToolViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Controllers/SignInViewController.swift
  Puhaha/Puhaha/Controllers/SingInViewControllerASDelegate.swift
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Global/Extensioon/UITextField+SetUnderLine.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Models/Meal.swift
Labels: enhancement, 우기, 콜리

#78 [FIX] setUnderLine -> Divider
  Puhaha/Puhaha/Controllers/JoinFamilyViewController.swift
Labels: BUG, 콜리, UI

#86 내비게이션 에러 수정 및 리엑션 추가 즉시 적용 추가
  Puhaha/Puhaha/AppDelegate.swift
  Puhaha/Puhaha/Controllers/ArchiveViewController.swift
  Puhaha/Puhaha/Controllers/MealDetailViewController.swift
  Puhaha/Puhaha/Controllers/SettingViewController.swift
  Puhaha/Puhaha/Models/Meal.swift
  Puhaha/Puhaha/Views/EmoticonView.swift
Labels: BUG, 우기, FEAT

#85 [ADD] 태그 메뉴 및 기분 수정
  Puhaha/Puhaha/Controllers/UploadViewController.swift
  Puhaha/Puhaha/Models/UploadTag.swift
Labels: 레나, ADD

#87 [FEAT] 회원탈퇴 구현
  Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
  Puhaha/Puhaha/Manager/FirestoreManager.swift
  Puhaha/Puhaha/Manager/StorageManager.swift
Labels: 레나, 우기, 콜리, FEAT
